"""Initial clean slate

Revision ID: 7fa46492fadc
Revises: 
Create Date: 2025-04-17 17:16:25.737270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa46492fadc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nombre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nombre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nombre_nombre'), ['nombre'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_usuario'), ['usuario'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('nombre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nombre_id'], ['nombre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_usuario'))

    op.drop_table('usuario')
    with op.batch_alter_table('nombre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nombre_nombre'))

    op.drop_table('nombre')
    # ### end Alembic commands ###
