"""Remove of 'Apellido'

Revision ID: a2ceb3ee2574
Revises: dc3cc275c80a
Create Date: 2025-03-26 18:59:45.146104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ceb3ee2574'
down_revision = 'dc3cc275c80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nombre', schema=None) as batch_op:
        batch_op.drop_index('ix_nombre_apellido')
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nombre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_index('ix_nombre_apellido', ['apellido'], unique=False)

    # ### end Alembic commands ###
