"""nombres table

Revision ID: b66d231d80c4
Revises: bf35d0fd6175
Create Date: 2025-03-26 11:13:16.530956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66d231d80c4'
down_revision = 'bf35d0fd6175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nombre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellido', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nombre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nombre_apellido'), ['apellido'], unique=True)
        batch_op.create_index(batch_op.f('ix_nombre_nombre'), ['nombre'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('nombre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nombre_id'], ['nombre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    with op.batch_alter_table('nombre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nombre_nombre'))
        batch_op.drop_index(batch_op.f('ix_nombre_apellido'))

    op.drop_table('nombre')
    # ### end Alembic commands ###
